### ISSUE TITLE
Incorrect hover text color bug in the header

### ISSUE THREAD

**Issue by JayanAXHF** [3b1b/3Blue1Brown.com#323]
When you go to the header on [3blue1brown.com](https://www.3blue1brown.com/) and hover on the background, the color for the page titles turns grey:
![image](https://user-images.githubusercontent.com/73993003/215278508-16a7e895-fe64-41b2-a6ac-7ea6872bd2d5.png)

## Steps to reproduce
1. Go to [3blue1brown.com](https://www.3blue1brown.com/).
2. Hover over the header and observe

**Comment by vincerubinetti** [comment]
Not really a bug but a limitation of CSS at the time. But now this can be fixed with widespread browser support of `:has()`: 

```css
.link:hover { color: blue };

header:has(.link:hover) .link:not(:hover) { opacity: 0.5 }
```
