### ISSUE TITLE
Patreon name list near lesson footer

### ISSUE THREAD

**Issue by vincerubinetti** [3b1b/3Blue1Brown.com#7]
Put list of Patreon supporters at bottom of each lesson. Those who contributed between a month leading up to the lesson's release?

Maybe pull from Patreon API? Or perhaps more simply, just make `_data/patrons.yaml` like:

```yaml
# a supporter
- name: Adrienne Wilson
  start: 2020-10-24
  end: 2018-08-10
  star: true


# another supporter
...
```

Maybe have a `special` field for people who have supported > 1 year or high donation amounts, and highlight them in bold or gold or something?
